import time
x=eval(input("enter the x value"))
y=eval(input("enter the y value"))
print(" -------the arithmetic operations ------------")
print("the sum is",x+y)
print("the sub is ",x-y)
print("the multipliication is ",x*y)
print("the division is",x/y)
print("the modulus division is",x%y)
print("the flloor division is",x//y)
print()
print("the power of ",x**y)
time.sleep(1)
print('end of an application')