import time
pid=input("enter the pid")
pname=input("enter the priduct name")
price=float(input("enter the price "))
company=input("enter the company")
print("-----------product information is---------------")
print("product name is",pname)
print("pid is",pid)
print("price of product ",price)
print("company of product is",company)
print("---------------------------")
time.sleep(1)
print("end of ann applkication")
